name: Pull, Scan and Push Docker Image to JFrog

on:
  issues:
    types: [closed]
  workflow_dispatch:
env:
  IMAGE_NAME: ${{ github.event.issue.title }}

jobs:
  push-to-jfrog:
    runs-on: ubuntu-latest
    if: github.event.issue.state_reason == 'completed'
    outputs:
      DATE_AND_TIME_OF_APPROVAL: ${{ steps.set-variables.outputs.DATE_AND_TIME_OF_APPROVAL }} 
      USER_WHO_APPROVED_OR_DENIED: ${{ steps.set-variables.outputs.USER_WHO_APPROVED_OR_DENIED }}
    permissions:
      issues: write
      contents: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set JFROG_IMAGE_NAME
        run: echo "JFROG_IMAGE_NAME=$(echo ${{ secrets.JF_URL }} | awk -F 'https://' '{print $2}')/docker/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

              
#-------------- JFROG UPLOAD IMAGE ------------------
  

      # - name: Setup JFrog CLI
      #   uses: jfrog/setup-jfrog-cli@v3
      #   env:
      #     JF_URL: ${{ secrets.JF_URL }}
      #     JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      # - name: Tag and Push Docker Image to JFrog
      #   id: jfrog-push
      #   run: |
      #     JFROG_IMAGE_NAME=$( echo ${{ secrets.JF_URL }} | awk -F 'https://' '{print $2}')/docker/$IMAGE_NAME
      #     docker tag $IMAGE_NAME $JFROG_IMAGE_NAME
      #     jf docker push $JFROG_IMAGE_NAME --build-name=$IMAGE_NAME --build-number=${{ github.run_number }}

      - name: Comment vulnerability summary
        # f: steps.jfrog-push.outcome == 'success'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue comment ${{ github.event.issue.number }} -b "👋 Thanks for submitting the request! The image has been approved and uploaded to the company's registry. You can find it in $FROG_IMAGE_NAME"

