name: Secret Scan

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  secret_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install TruffleHog
        run: |
          pip install trufflehog


# The pull reques is from the test branch to the dev branch. The only thing that will be scanned is the diff between the two branches.
# use trufflehog github action to scan for secrets

      - name: Scan for secrets
        run: |
            trufflehog --json --since-commit $(git merge-base origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }}) --branch $(${{ github.event.pull_request.head.ref }}) --repo

