name: Secret Scan

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  secret_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: TruffleHog OSS
  # You may pin to the exact commit or the version.
  # uses: trufflesecurity/trufflehog@a9b056de0a2d1cc78da55c3594b194bf237663ef
        uses: trufflesecurity/trufflehog@v3.62.1
        with:
          # Repository path
          path: ./
          base: main
          head: HEAD
                
