name: trivy scan

on:
  workflow_call:
    inputs:
      image-to-analyze:
        required: true
        type: string
      trivy-scan-options:
        required: false
        default: 'image' 
        type: string
jobs: 
   trivy_image_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Image Scan with Trivy
      run: |
        # if you want to buld the image, you can use the following command
        # docker build -t ${{ env.DOCKER_IMAGE }} .
        
        # if you want to scan the image from a private registry, you need to login first
        # docker login -u ${{ env.REGISTRY_USERNAME }} -p ${{ env.REGISTRY_PASSWORD }} ${{ env.REGISTRY_URL }}
        
        docker pull ${{ input.image-to-analyze }}
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/home aquasec/trivy ${{ input.image-to-analyze }} ${{ env.DOCKER_IMAGE }} --format json -o /home/trivy-image-report.json
      continue-on-error: true

    - name: Upload Trivy Scan Report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-scan-report
        path: trivy-image-report.json
